spring:
  application:
    name: "fmk00_jbpm-test"
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:./target/spring-boot-jbpm
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        hbm2ddl:
          auto: update
    hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jta:
    narayana:
      transaction-manager-id: 1

cxf:
  path: /rest

#kie server config
kieserver:
  serverId: "fmk00_jbpm-test"
  serverName: "fmk00_jbpm-test"
  location: http://localhost:8080/rest/server
  controllers: http://localhost:8081/business-central/rest/controller
  classPathContainer: true
  autoScanDeployments: true
  drools:
    enabled: true
  dmn:
    enabled: true
  jbpm:
    enabled: true
  jbpmui:
    enabled: true
  casemgmt:
    enabled: true
#  prometheus:
#    enabled: false
  swagger:
    enabled: true
  
  
#jbpm configuration
jbpm:
  executor:
    enabled: false
#    retries: 5
#    interval: 3
#    threadPoolSize: 1
#    timeUnit: SECONDS